#!/bin/bash
echo "Updating SkyWire..."
cd /usr/local/go/src/github.com/skycoin/skywire
git pull origin master
cd /usr/local/go/src/github.com/skycoin/skywire/cmd
[[ -d /usr/local/go/pkg/linux_arm64/github.com/skycoin ]] && rm -rf /usr/local/go/pkg/linux_arm64/github.com/skycoin
go install ./...
echo "Updating SkyWire Script..."
cd /usr/local/skywire-script
git pull origin master
cd /usr/local/skywire-script
cp 10-header /etc/update-motd.d/
cp 99-point-to-faq /etc/update-motd.d/

[[ -f /tmp/skywire-pids/manager.pid ]] && pkill -F /tmp/skywire-pids/manager.pid
[[ -f /tmp/skywire-pids/node.pid ]] && pkill -F /tmp/skywire-pids/node.pid

echo "Rebooting..."
reboot